format = """$directory\
$git_branch\
$git_status\
\n\
$character"""

[directory]
style = "white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
".config" = ""

[git_branch]
symbol = " "

[git_status]
ahead = ""
behind = ""
